# Generated by Django 5.2.7 on 2025-10-20 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('org_code', models.SlugField(unique=True)),
                ('country_code', models.CharField(default='BJ', max_length=2)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('address', models.TextField(blank=True)),
                ('trade_register', models.CharField(blank=True, max_length=64)),
                ('tax_id', models.CharField(blank=True, max_length=64)),
                ('tax_enabled', models.BooleanField(default=True)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('whatsapp_number', models.CharField(blank=True, max_length=32)),
                ('brand_color', models.CharField(default='#111827', max_length=9)),
                ('logo_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('ACCOUNTANT', 'Comptable'), ('SALES', 'Commercial'), ('WAREHOUSE', 'Logistique'), ('VIEWER', 'Lecture')], default='VIEWER', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.organization')),
            ],
            options={
                'unique_together': {('organization', 'user')},
            },
        ),
    ]
